### ISSUE TITLE
estimateGas returns undefined result and no error

### ISSUE THREAD

**Issue by yann300** [WalletConnect/walletconnect-monorepo#334]
calling `eth_estimateGas` on a failing transaction returns:
```
jsonrpc: "2.0"
result: undefined
```
seems like the `error` property is missing.

I am using the provider 
`import WalletConnectProvider from "@walletconnect/web3-provider";`
from `this.provider = await web3Modal.connect()`

The call to `estimateGas` succeed if the transaction doesn't fail.

```
jsonrpc: "2.0"
method: "eth_estimateGas"
params: Array(1)
0:
 data: "0xd98471b2"
 from: "0xdfb0c20131328c90cc58650a3231695042a28875"
 to: "0x47e4783eaf21343166651f2fd98d1d9dfb0929de"
 value: "0x0"
```

```
curl https://ropsten.infura.io/v3/83d4d660ce3546299cbe048ed95b6fad \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_estimateGas","params": [{"from": "0xdfb0c20131328c90cc58650a3231695042a28875","to": "0x47e4783eAF21343166651f2Fd98D1D9dfb0929De","value": "0x0","data": "0xd98471b2"}],"id":234}'	
```
